apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "helm.labels" . | nindent 4 }}
  name: {{ include "helm.fullname" . }}-ml-api
spec:
  ports:
    - port: 3333
      targetPort: ml-api
{{- if .Values.mlApi.nodePort }}
      nodePort: {{ .Values.mlApi.nodePort }}
  type: NodePort
{{- end }}
  selector:
    obico.deployment: ml-api
