{{- if not .Values.email.secret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ include "helm.labels" . | nindent 4 }}
  name: {{ include "helm.fullname" . }}-email
data:
  {{ with .Values.email }}
  EMAIL_HOST: '{{ .host | b64enc }}'
  EMAIL_HOST_USER: '{{ .user | b64enc }}'
  EMAIL_HOST_PASSWORD: '{{ .password | b64enc }}'
  EMAIL_PORT: '{{ .port | toString | b64enc }}'
  EMAIL_USE_TLS: '{{ include "helm.python.boolean" .useTls | b64enc }}'
  DEFAULT_FROM_EMAIL: '{{ .fromAddress | b64enc }}'
  {{- end }}
{{- end }}
